### ISSUE TITLE
Frage bzgl. code.coding

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-prozedur#13]
[Kutaiba Saleh](https://simplifier.net/user/kutaibasaleh) commented about a year ago
Hi, ist es so gemeint/ gewollt, dass die Prozeduren nur mit einem Kode kodiert werden können "Entweder wird die Prozedur mit OPS oder SNOMED-CT kodiert." heißt das aber auch? man kann andere Kodes (z.B. Haus-Codes/ wie Copra) nicht verwenden. Also Beim validieren einer Procedur-Ressource mit mehr als einem zusätzliche Kode zu OPS oder Snomed gibt ein Fehler zurück: Invalid : Instance count for 'Procedure.code.coding:ops' is 2, which is not within the specified cardinality of 0..1 Außerdem wurden mehrere Errors beim validieren des Beispiels, was hier gestllt wurde, geworfen.
 avatar
[Andrea Essenwanger](https://simplifier.net/user/andreaessenwanger) commented about a year ago
Das Profil hat ein open Slicing auf .code jeweils mit Slices für OPS und SCT. Die Slices selber haben eine Kardinalität von 0..1, weil es ja nur einen Code pro System geben sollte, womit das darzustellende CodeableConcept kodiert wird. Sobald es mehr als einen OPS oder SCT Code gibt, handelt es sich doch eig um ein anderes medizinisches Konzept welches hierbei abgebildet wird oder nicht? Hauscodes, sollten aus anderen Systemen kommen und sollten auch problemlos vom Profil erlaubt werden. Welche Codes haben denn genau den Fehler ausgelöst?
 avatar
[Julia Palm](https://simplifier.net/user/juliapalm) commented about a year ago
Das Problem ist, dass Ressourcen einen Validierungsfehler werfen, sobald mehr als ein CodeSystem verwendet wird. Also wenn man einen OPS und einen SCT Code in die Ressource schreibt (so wie in den Beispielressourcen im Profil), dann wirft die Validierung einen Fehler. Obwohl man die Kardinalität der einzelnen Slices damit ja einhält. [Diese Ressource](https://simplifier.net/MedizininformatikInitiative-ModulProzeduren/ExampleProcedure/%7Ejson) wirft den Fehler z.B.
 avatar
[Kutaiba Saleh](https://simplifier.net/user/kutaibasaleh) commented about a year ago
kann jemand bitte das Issue weiterbearbeiten?

**Comment by julsas** [comment]
siehe #10
