### ISSUE TITLE
Dependency auf de.basisprofil.r4 1.4.0 aktualisieren

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-prozedur#16]
[Kutaiba Saleh](https://simplifier.net/user/kutaibasaleh) commented about a year ago
Um die KDS-Packages verwenden zu können, müssen alle KDS-Packages auf die gleiche Version des Basisprofils verweisen https://simplifier.net/packages/de.basisprofil.r4/1.4.0

**Comment by julsas** [comment]
@julsas package.json im repo anpassen
