### ISSUE TITLE
No-Break Space in OPS.json

### ISSUE THREAD

**Issue by culpinnis** [medizininformatik-initiative/kerndatensatzmodul-prozedur#2]
Hi there, 

We (UKL) wanted to use the OBS.json in a Vonk FHIR server to validate our FHIR resources. 
Unfortunately, the server returns a lot of errors when importing the CodeSystem. 

It seems that all errors are related to notes: 

````
"Value 'Diese Kodes sind nur zu verwenden bei Diagnostik nach der jeweils gültigen Fortschreibung der Richtlinie der Bundesärztekammer zur Feststellung des irreversiblen Hirnfunktionsausfalls (siehe im Zusammenhang mit einer Organspende auch § 5 und § 16 Abs. 1 Satz 1 Nr. 1 Transplantationsgesetz)' does not match regex '[ \\r\\n\\t\\S]+'"
````

Well, the regex `[ \r\n\t\S]+` matches all valid symbols and tabstops, newlines, carriage returns...
So I started to investigate the file in detail. Looking at the file in a hex editor we can see invisible characters: 

![image001](https://user-images.githubusercontent.com/2099798/98685929-42d8af80-2368-11eb-8988-9924ffda2f98.png)

Every note that includes the hex byte C2 will result in an error during the validation. 
This character is for example also present at most of the dots after an age: 18. Lebensjahres; 14. Lebensjahres etc. 
I removed the character for one single note and afterwards the entry was processed fine. 
I have tested several versions of the file (simplifier.net and GitHub) so far with the same result. 

Best wishes
Chris Ulpinnis

**Comment by culpinnis** [comment]
Please note that icd-10-gm.json seems to have the same issue. In that file, it occurs before roman numbers, maybe a formating issue of the text source.

**Comment by culpinnis** [comment]
Further investigation resulted in the knowledge that C2A0 is the No-Break Space in UTF-8. It seems that this character is no accepted by Vonk (I guess \S does not match it). 
I was able to fix the file by running 

```
perl -i -p -e "s/[\xC2][\xA0]/\x20/g" file.json
```

**Comment by alexzautke** [comment]
Thanks @culpinnis for the investigation. It will probably take some time until we can fix this in the release, but it's good to know that you have found a workaround for now!

**Comment by alexzautke** [comment]
Looking at the datatype description of string (https://www.hl7.org/fhir/datatypes.html#string), it seems that the code point should be allowed but is simply mismatched in the .NET FHIR API. So I think that the CodeSystem itself is correct and this is a Vonk/.NET Issue. As soon as I have a bug ticket for the .NET API, I will update the ticket here.

**Comment by alexzautke** [comment]
Created https://github.com/FirelyTeam/firely-net-sdk/issues/1563. All further updates are discussed there.
