### ISSUE TITLE
category slicing

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-prozedur#3]
siehe auch: https://github.com/hl7germany/forschungsnetz-covid19/issues/26

Unordered, Open, by system(Pattern)
sollte sein:
Unordered, Open, by &this(Pattern)

**Comment by alexzautke** [comment]
Fixed in https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.prozedur/1.0.4
