### ISSUE TITLE
Remove extra spaces in search parameter expression

### ISSUE THREAD

**Issue by schwzr** [medizininformatik-initiative/kerndatensatzmodul-prozedur#45]
As reported by @juliangruendner [here](https://mii.zulipchat.com/#narrow/stream/387220-Blaze-Support/topic/.E2.9C.94.20code.20search.20extension/near/435144600), there are extra spaces in the expression of the SearchParameter "durchfuehrungsabsicht".

https://github.com/medizininformatik-initiative/kerndatensatzmodul-prozedur/blob/368ca96dff8dd1ae53c397380c58447f02cfd891/input/fsh/searchparameters/mii-sp-prozedur-durchfuehrungsabsicht.fsh#L15

**Comment by julsas** [comment]
wird korrigiert

**Comment by julsas** [comment]
ist in Modul Meta umgezogen und korrigiert

https://github.com/medizininformatik-initiative/kerndatensatz-meta/blob/f912b7d6f032bfbc3335f99b0f0e3ea02c6ab69c/input/fsh/searchparameters/mii-sp-meta-procedure-durchfuehrungsabsicht.fsh#L17
