### ISSUE TITLE
ValueSet 'MII_VS_Prozedur_OpsKategorien_SNOMEDCT'

### ISSUE THREAD

**Issue by LukasGoetz** [medizininformatik-initiative/kerndatensatzmodul-prozedur#46]
Hallo,
der Displayname "Administration of medicine" fuer den Snomed-CT Code "18629005" ist falsch. Es muesste "Administration of medication" lauten.
`Error @ Procedure.category.coding[0].display (line 1, col592): Wrong Display Name 'Administration of medicine' for http://snomed.info/sct#18629005. Valid display is one of 7 choices: 'Administration of medication', 'Giving medication', 'Medication administration', 'Medication administration treatments and procedures', 'Medication treatment', 'Administration of drug or medicament (procedure)' or 'Administration of drug or medicament' (for the language(s) '--')`

**Comment by ThomasDeBe** [comment]
Hier ist die Frage, ob wir displaynamen von SNOMED überhaupt ins Pattern aufnehmen sollten. Das macht es einfacher für Lesbarkeit des Profils und für Qualtiy Assurance, aber die können sich auch mal schnell von einer Edition zur anderen ändern. Würde das bei so einem allgemeinen Modul rausnehmen

**Comment by julsas** [comment]
@LukasGoetz korrekt, wird korrigiert.

@ThomasDeBe korrekt, displays besser nicht ins pattern, ist es hier auch nicht. Hier geht es um display im ValueSet.
